import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RegisterComponent } from './register/register.component';

import {
  MatToolbarModule,
  MatSortModule,
  MatButtonModule,
  MatButtonToggleModule,
  MatCardModule,
  MatCheckboxModule,
  MatSnackBarModule,
  MatDialogModule,
  MatIconModule,
  MatSliderModule,
  MatTabsModule,
  MatSlideToggleModule,
  MatSidenavModule,
  MatExpansionModule,
  MatFormFieldModule,
  MatListModule,
  MatMenuModule,
  MatRadioModule,
  MatTooltipModule,
  MatProgressSpinnerModule,
  MatProgressBarModule,
  MatGridListModule,
  MatSelectModule,
  MatStepperModule,
  MatChipsModule,
  MatAutocompleteModule,
  MatPaginatorModule,
  MatInputModule,
  MatDatepickerModule,
  MatTableModule
} from '@angular/material';
import { AccountService } from './account.service';
import { ReactiveFormsModule, FormsModule } from '@angular/forms';
import { LoginComponent } from './login/login.component';


@NgModule({
  imports: [
    FormsModule,
    ReactiveFormsModule,
    CommonModule,
    MatToolbarModule,
  MatSortModule,
  MatButtonModule,
  MatButtonToggleModule,
  MatCardModule,
  MatCheckboxModule,
  MatSnackBarModule,
  MatDialogModule,
  MatIconModule,
  MatSliderModule,
  MatTabsModule,
  MatSlideToggleModule,
  MatSidenavModule,
  MatExpansionModule,
  MatFormFieldModule,
  MatListModule,
  MatMenuModule,
  MatRadioModule,
  MatTooltipModule,
  MatProgressSpinnerModule,
  MatProgressBarModule,
  MatGridListModule,
  MatSelectModule,
  MatStepperModule,
  MatChipsModule,
  MatAutocompleteModule,
  MatPaginatorModule,
  MatInputModule,
  MatDatepickerModule,
  MatTableModule,
  ],
  exports: [
    MatToolbarModule,
  MatSortModule,
  MatButtonModule,
  MatButtonToggleModule,
  MatCardModule,
  MatCheckboxModule,
  MatSnackBarModule,
  MatDialogModule,
  MatIconModule,
  MatSliderModule,
  MatTabsModule,
  MatSlideToggleModule,
  MatSidenavModule,
  MatExpansionModule,
  MatFormFieldModule,
  MatListModule,
  MatMenuModule,
  MatRadioModule,
  MatTooltipModule,
  MatProgressSpinnerModule,
  MatProgressBarModule,
  MatGridListModule,
  MatSelectModule,
  MatStepperModule,
  MatChipsModule,
  MatAutocompleteModule,
  MatPaginatorModule,
  MatInputModule,
  MatDatepickerModule,
  MatTableModule,
  ],
  declarations: [RegisterComponent, LoginComponent],
  entryComponents: [RegisterComponent, LoginComponent],
  providers: [AccountService]
})
export class AccountModule { }
